### PR TITLE
make StillPicture(), jumping to marks, moving marks faster (very fast…

### PR DESCRIPTION
**Pull request by j1rie**
… for vdpau)

### CODE REVIEW

**Comment by j1rie** [comment]
I have tested this, but please test again before commiting.

**Comment by j1rie** [comment]
And please see https://www.vdr-portal.de/forum/index.php?thread/136385-softhdevice-softhdcuvid-und-andere-softhd-s/
Maybe you can help?

**Comment by j1rie** [comment]
Forgot to raise to VIDEO_SURFACES_MAX * 2 for Vaapi.
Will make a commit in a few days.

**Comment by ua0lnj** [comment]
I once spent a lot of time on a still image, so this won't be a quick process.

**Comment by j1rie** [comment]
I've fixed interlaced playback stillpicture jumping. And doubled vaapi ringbuffer. I don't have vaapi grafic card, so I can't test it.

**Comment by ua0lnj** [comment]
VIDEO_SURFACES_MAX * 2 not need for vdpau and vaapi.
Deinterlace with vdpau not works (in live and replay mode).
vaapi not tested yet, but this was done for a reason, it was not a mistake.
If i return back VIDEO_SURFACES_MAX to vdpau, all works normal, still picture hasn't gotten any worse.


upd
"I've fixed interlaced playback stillpicture jumping. And doubled vaapi ringbuffer. I don't have vaapi grafic card, so I can't test it."
- not helped, I don't see any difference.

upd
interlace still picture is deinterlacing with cuvid and nvdec only.

**Comment by j1rie** [comment]
Speaking about vdpau:
How many frames arive depends on
    for (i = 0; i < (VideoIsDriverCuvid() ? 12 : 6); ++i) {
in StillPicture(). So 6 for vdpau.
That’s why I increased VIDEO_SURFACES_MAX, so that all 6 frames have place in ringbuffer at once. Without increasing VIDEO_SURFACES_MAX, only 4 frames get stored, but it works with 4 frames, too. Just the time for a stillpicture raises than from ~70 ms to ~80ms, which is acceptable.

I admit, increasing VIDEO_SURFACES_MAX was a bit brute. So reverting increasing VIDEO_SURFACES_MAX is the best thing to do, I guess.

If I change it to
    for (i = 0; i < (VideoIsDriverCuvid() ? 12 : 4); ++i) {
the time for a stillpicture does not increase.
I am not sure, if this might have other side effects.

And yes, I see, deinterlace doesn’t happen for vdpau stillpicture.
Only frames with key_frame value 1 arrive, while for cuvid key_frame value 1 and key_frame value 0 alternate.

**Comment by j1rie** [comment]
> Only frames with key_frame value 1 arrive, while for cuvid key_frame value 1 and key_frame value 0 alternate.

That is already the case with your current git, so is not caused by my stillpicture commits.

**Comment by j1rie** [comment]
> and nvdec key_frame value 1 and key_frame value 0 alternate.

Not true. nvdec same as vdpau only key_frame value 1.

**Comment by j1rie** [comment]
The main question is still, why avcodec_free_context() and avcodec_flush_buffers() and avcodec_open2() together take so much time in case of cuvid and nvdec.

**Comment by j1rie** [comment]
It seems to be normal, that cuvid is so slow: https://www.vdr-portal.de/forum/index.php?thread/136385-softhdevice-softhdcuvid-und-andere-softhd-s/&postID=1373383#post1373383

**Comment by j1rie** [comment]
I’ve reverted a few things, and what’s left is
* decode all stillpicture data at once (as much as allowed by ringbuffer size)
* advance the decoded frames immediately
My attempts to improve cuvid and nvdec timings took much time, but no result. It’s the first time I am working on ffmpeg stuff. I wonder how come @jojo61's code is faster. I am about to give up.

**Comment by ua0lnj** [comment]
I have some thoughts, but I don't have time to test them yet.
I'll try next week.

**Comment by ua0lnj** [comment]
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/5bb235eb711c53a3980efde0fec64b95089b93f9
The code is simpler, and the cuvid is better.
But 10-bit hevc without a picture with stillpicture, only cuvid is fine. I'll look at it later.

**Comment by j1rie** [comment]
I like your simplified code.

But how about those commits:
[tell VideoDriver](https://github.com/ua0lnj/vdr-plugin-softhddevice/pull/91/commits/87ade09f38989fe38bea5565b5911d483108db62)
[cleanup](https://github.com/ua0lnj/vdr-plugin-softhddevice/pull/91/commits/f5b9f926aa4d083a453e23bcbceb68f792013fd0)
[increase VideoSoftStartFrames (100 was not enough)](https://github.com/ua0lnj/vdr-plugin-softhddevice/pull/91/commits/23b4002c1313dfdf67f42bb863f8281f37071434)
[patch for vdr: play after slow-forward](https://github.com/ua0lnj/vdr-plugin-softhddevice/pull/91/commits/52be0c705e8c35225512511f9409b5334f40941d)

Github has put all my later pull requests into this one, until you closed it.
I don't know, how to fix it. What can I do to clean up the mess?
I want to avoid hard reset, if there is another way.

**Comment by ua0lnj** [comment]
We'll discuss the patch on the forum, I'll look at the other commits.
Perhaps you need to do a git sync, without a hard reset, to get to the current state, I don't know yet.

**Comment by j1rie** [comment]
So far my plan is to create a new branch, in order to be able to make pull requests again. With my current 'latest' branch new pull requests create a big mess.
And in the future I need to put pull requests in extra branches, so that this will not happen again.
So I will start working with branches and then I will make new pull requests for the other commits.

**Comment by ua0lnj** [comment]
And if you then delete the branch from which the commits were made, what will happen in the history, a non-working link?

**Comment by j1rie** [comment]
[https://www.atlassian.com/git/tutorials/merging-vs-rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing)
-> Integrating an approved feature

[https://graphite.dev/guides/git-rebase-vs-fast-forward#1-what-is-a-git-fast-forward](https://graphite.dev/guides/git-rebase-vs-fast-forward#1-what-is-a-git-fast-forward)

I hope it will work as described in the 2 links.
I have never done it before, so I will learn hopefully.

**Comment by j1rie** [comment]
I just created a new branch, did a hard reset in the new branch, pulled your commits, cherry-picked my commits, and pushed it.

**Pull request closed without merging**
