### PR TITLE
early audio/video sync + insert silence (part 2)

### PR DESCRIPTION
**Pull request by j1rie**

### CODE REVIEW

**Comment by ua0lnj** [comment]
For me the best one is the accurate switch, the silence insertion does not crackle, but the sound appears much later on some channels.

**Comment by j1rie** [comment]
Just curious, which are those channels?
I am glad to know, that the accurate switch is the best for you.

**Comment by ua0lnj** [comment]
iptv udp, h.264 25 Hz progressive sd, my local iptv provider.
With silence:

Jul 10 21:12:55 ua0lnjvdr vdr: video: initial slow down video, frame 5
Jul 10 21:12:55 ua0lnjvdr vdr: video: 21:18:48.599+8888    0   0/\ms   0+3+0 v-buf
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?   32ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?   54ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?   75ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?   96ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?  118ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start?  139ms skip 0ms
Jul 10 21:12:55 ua0lnjvdr vdr: audio: start audio after waiting for enough audio
Jul 10 21:12:55 ua0lnjvdr vdr: audio: ----> 139ms start
Jul 10 21:12:55 ua0lnjvdr vdr: codec/audio: inital drift delay 160ms
Jul 10 21:12:55 ua0lnjvdr vdr: video/nvdec: diff -11365 -126 lim -65 fill 4
Jul 10 21:12:55 ua0lnjvdr vdr: video: initial slow down video, frame 9
Jul 10 21:12:55 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:55 ua0lnjvdr vdr: video: 21:18:48.599 -126  187   0/\ms   2+5+0 v-buf
Jul 10 21:12:55 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:55 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1005/12) 0 v-buf closing 0
Jul 10 21:12:55 ua0lnjvdr vdr: video: 21:18:48.759  -46  107   0/\ms   0+3+0 v-buf
Jul 10 21:12:55 ua0lnjvdr vdr: video/nvdec: diff -5970 -66 lim -65 fill 4
Jul 10 21:12:55 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:55 ua0lnjvdr vdr: video: 21:18:48.759  -66  237   0/\ms   1+5+0 v-buf
Jul 10 21:12:55 ua0lnjvdr vdr: video/nvdec: diff -4159 -46 lim -65 fill 3
Jul 10 21:12:55 ua0lnjvdr vdr: video/nvdec: synced after 17 frames 1379ms
Jul 10 21:12:56 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1006/44) 0 v-buf closing 0
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.399  -45  108   0/\ms   0+3+0 v-buf
Jul 10 21:12:56 ua0lnjvdr vdr: stop playing samples from ringbuffer
Jul 10 21:12:56 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1007/44) 0 v-buf closing 0
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.399  -66   88   0/\ms   0+3+0 v-buf
Jul 10 21:12:56 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1009/44) 0 v-buf closing 0
Jul 10 21:12:56 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.399 -126   91   0/\ms   0+3+0 v-buf
Jul 10 21:12:56 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1010/46) 0 v-buf closing 0
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.439 -106   72   0/\ms   0+3+0 v-buf
Jul 10 21:12:56 ua0lnjvdr vdr: audio/alsa: wait underrun error? 'Broken pipe'
Jul 10 21:12:56 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1013/46) 0 v-buf closing 0
Jul 10 21:12:56 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.439 -114  192   0/\ms   2+5+0 v-buf
Jul 10 21:12:56 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:56 ua0lnjvdr vdr: video: slow down video, duping frame
Jul 10 21:12:56 ua0lnjvdr vdr: resume playing samples from ringbuffer
Jul 10 21:12:56 ua0lnjvdr vdr: video: 21:18:49.619  +65  362   0/\ms   1+8+0 v-buf
Jul 10 21:12:57 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1015/104) 0 v-buf closing 0
Jul 10 21:12:57 ua0lnjvdr vdr: video: 21:18:50.599  +46  195   0/\ms   0+3+0 v-buf
Jul 10 21:12:57 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1020/112) 0 v-buf closing 0
Jul 10 21:12:57 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:57 ua0lnjvdr vdr: video: 21:18:50.759  -73  234   0/\ms   2+5+0 v-buf
Jul 10 21:12:57 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1021/122) 0 v-buf closing 0
Jul 10 21:12:57 ua0lnjvdr vdr: video: 21:18:50.959  -53  119   0/\ms   0+3+0 v-buf
Jul 10 21:12:57 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:57 ua0lnjvdr vdr: video: 21:18:50.959  -73  205   0/\ms   1+5+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1022/144) 0 v-buf closing 0
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.399  -53  105   0/\ms   0+3+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: stop playing samples from ringbuffer
Jul 10 21:12:58 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1023/144) 0 v-buf closing 0
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.399  -73   85   0/\ms   0+3+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1026/144) 1 v-buf closing 0
Jul 10 21:12:58 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.399 -153   26   0/\ms   0+3+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: audio/alsa: wait underrun error? 'Broken pipe'
Jul 10 21:12:58 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1027/146) 0 v-buf closing 0
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.439 -115   25   0/\ms   0+3+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: video: decoder buffer empty, duping frame (1030/146) 4 v-buf closing 0
Jul 10 21:12:58 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.439 -115  196   0/\ms   2+5+0 v-buf
Jul 10 21:12:58 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 21:12:58 ua0lnjvdr vdr: video: slow down video, duping frame
Jul 10 21:12:58 ua0lnjvdr vdr: resume playing samples from ringbuffer
Jul 10 21:12:58 ua0lnjvdr vdr: video: 21:18:51.619  +64  345   0/\ms   1+8+0 v-buf

synchronization occurs earlier, but the sound disappears several times


With accurate:
Jul 10 22:18:31 ua0lnjvdr vdr: video: initial slow down video, frame 5
Jul 10 22:18:31 ua0lnjvdr vdr: video: 22:24:24.599+8888    0   0/\ms   0+5+0 v-buf
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  118ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  139ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  160ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  182ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: [softhddev]GetVideoSize: 800x450 1,81818
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  203ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  224ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  246ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  267ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  288ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  310ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  331ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  352ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  374ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  395ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  416ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  438ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  459ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  480ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  502ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  523ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  544ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  566ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  587ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  608ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  630ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  651ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  672ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  694ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  715ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  736ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  758ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  779ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start?  800ms skip 0ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio: start audio after waiting for enough audio
Jul 10 22:18:31 ua0lnjvdr vdr: audio: ----> 800ms start
Jul 10 22:18:31 ua0lnjvdr vdr: codec/audio: inital drift delay 800ms
Jul 10 22:18:31 ua0lnjvdr vdr: audio/alsa: wait underrun error? 'Broken pipe'
Jul 10 22:18:31 ua0lnjvdr vdr: video/nvdec: diff -12008 -133 lim -65 fill 4
Jul 10 22:18:31 ua0lnjvdr vdr: video: initial slow down video, frame 44
Jul 10 22:18:31 ua0lnjvdr vdr: video: speed up video, droping frame
Jul 10 22:18:31 ua0lnjvdr vdr: video: 22:24:24.599 -133  820   0/\ms  18+5+0 v-buf
Jul 10 22:18:32 ua0lnjvdr vdr: video/nvdec: diff -4816 -53 lim -65 fill 4
Jul 10 22:18:32 ua0lnjvdr vdr: video/nvdec: synced after 50 frames 1734ms

synchronization occurs later, but the sound is normal immediately and does not interrupt

**Comment by j1rie** [comment]
Yes, on some channels (which I use only for testing), I see this, too.

But on the channels I use mostly, silence interrupting audio is rare, and the faster sync is more important for me.

**Pull request merged**
