### PR TITLE
don't start before AudioSkip is exhaustet, further improve jumps during replay, tighter sync, sync range depends on Interlaced, improve sync logic

### PR DESCRIPTION
**Pull request by j1rie**

### CODE REVIEW

**Comment by ua0lnj** [comment]
Makes it worse:
https://github.com/ua0lnj/vdr-plugin-softhddevice/pull/60/commits/1f135fb24bcd5ce4fe6fa7fec26f47a26f7c695b

I didn't notice any difference from the others.

**Comment by ua0lnj** [comment]
https://www.4shared.com/s/fYMK46pd3ge
You can test this record without patch and with patch.
I'm worse with the patch.

**Comment by j1rie** [comment]
I can receive FTV UHD. VLC says it's 25 Hz. What does worse exactly mean? I have only next week time to check thoroughly.

**Comment by ua0lnj** [comment]
When playing this recording, sound synchronization occurs 2 seconds after the start without a patch, and after 13 seconds with a patch. There are also records, when rewinding from the end to the beginning, the synchronization time is more than 500 frames
When switching channels, I did not notice the difference, with or without a patch, 2-3 seconds, I tested with soft avsync off, and vdpau or cuvid.

**Comment by j1rie** [comment]
Thanks for the info. I will look into it. The main advantage of the (video part) patch for me was, that without it I have drop/dupe on some stations, with the patch no drop/dupe any more. Those drop/dupe occur only sometimes, so maybe it was just luck. I will do more tests.

**Comment by j1rie** [comment]
Your recording has a huge audio video delay, so it is good for testing and exposing bugs not seen without such a big delay.
I have reproduced the problem you described, and will try  and see, if I can fix it, while keeping the idea of the patch.
This might not be easy and take a while.

**Comment by ua0lnj** [comment]
This recording was sent to me a long time ago by someone from the VDR forum.

**Comment by j1rie** [comment]
The issues with the FTV UHD recording are resolved and zapping is 25% faster.

**Comment by ua0lnj** [comment]
First impression is good, I will test again.

**Pull request merged**
