### PR TITLE
in case of fast sync or soft sync use old behaviour (part 2)

### PR DESCRIPTION
**Pull request by j1rie**
make the commit 'almost no more droping/duping after sync on SD' depended on accurate sync

### CODE REVIEW

**Comment by j1rie** [comment]
Again untested.

**Comment by ua0lnj** [comment]
Tested, ok. Now my 8 second delay file starts faster with "acurate" than with "fast" :)

**Comment by j1rie** [comment]
I plan to make VideoStartThreshold_SD configurable. When that's done, you could rename "fast" into "old" or "legacy".

**Comment by j1rie** [comment]
Maybe instead of making VideoStartThreshold_SD configurable, we could use 4 sync modes.
Old name                                   |   new name
„fast“                                        -> „early audio“
„soft“                                        -> „early audio + soft sync“ 
(accurate without SD buffering) -> „early sync + fast SD“
„accurate“                                 -> „early sync + accurate SD“
Having the choice of early sync + fast SD, might be more convincing for some users.

**Pull request merged**
